import { PatientClinicalRecord, MedicalHistory, ClinicalEvolution, PrescriptionItem } from "@/types/clinical-record";

export const DEFAULT_MEDICAL_HISTORY: MedicalHistory = {
  alergias: ["Nenhuma alergia medicamentosa relatada"],
  comorbidades: [],
  medicamentosUsoContinuo: [],
  tipoSanguineo: "O+",
  historicoCirurgico: "Nenhuma cirurgia prévia relatada.",
  historicoFamiliar: "Pais hipertensos sem histórico de neoplasias precoces.",
  habitosVida: {
    tabagismo: "Não fuma",
    etilismo: "Consumo social",
    atividadeFisica: "Moderada (1-3x/sem)",
  },
  observacoesGerais: "Paciente colaborativo, sem queixas agudas prévias.",
  updated_at: "2026-09-20T10:00:00Z",
};

export const INITIAL_CLINICAL_RECORDS: Record<string, PatientClinicalRecord> = {
  // Mariana Alcantara Silveira
  "e4a1f89b-9c7d-4a1b-8e2f-1a3b5c7d9e01": {
    client_id: "e4a1f89b-9c7d-4a1b-8e2f-1a3b5c7d9e01",
    medicalHistory: {
      alergias: ["Dipirona (urticária)", "Frutos do mar"],
      comorbidades: ["Rinite Alérgica Perene", "Dermatite Atópica Leve"],
      medicamentosUsoContinuo: ["Loratadina 10mg (SOS)", "Hidratante com Ureia 10%"],
      tipoSanguineo: "A+",
      historicoCirurgico: "Apendicectomia laparoscópica em 2018 sem intercorrências.",
      historicoFamiliar: "Mãe com hipotireoidismo de Hashimoto; Pai hipertenso.",
      habitosVida: {
        tabagismo: "Não fuma",
        etilismo: "Não consome",
        atividadeFisica: "Moderada (1-3x/sem)",
      },
      observacoesGerais: "Apresenta piora do quadro cutâneo em períodos de estresse profissional.",
      updated_at: "2026-09-22T14:30:00Z",
    },
    evolutions: [
      {
        id: "evo-101",
        client_id: "e4a1f89b-9c7d-4a1b-8e2f-1a3b5c7d9e01",
        data: "2026-09-25",
        horario: "09:30",
        tipo: "Consulta",
        profissional: "Dra. Juliana Sena",
        especialidade: "Clínica Geral & Dermatologia",
        subjetivo: "Paciente comparece relatando prurido cutâneo moderado em região flexural dos antebraços há 2 semanas. Nega febre, dispneia ou outros sintomas sistêmicos. Refere bom padrão de sono.",
        objetivo: "Bom estado geral, corada, hidratada, acianótica e anictérica. Lesões eritemato-descamativas leves em fossas antecubitais bilaterais. Sem sinais de infecção secundária ativa.",
        sinaisVitais: {
          pressaoArterial: "118/76",
          frequenciaCardiaca: 72,
          temperatura: 36.4,
          peso: 58.5,
          altura: 165,
          imc: 21.5,
        },
        avaliacao: "Dermatite atópica em exacerbação sazonal leve (CID-10 L20.9).",
        plano: "1. Prescrito Desonida 0,05% loção à noite por 7 dias nas lesões ativas.\n2. Manutenção de hidratante barreira 2x/dia após o banho.\n3. Evitar banhos quentes prolongados.\n4. Retorno de controle em 30 dias.",
        created_at: "2026-09-25T09:45:00Z",
      },
      {
        id: "evo-100",
        client_id: "e4a1f89b-9c7d-4a1b-8e2f-1a3b5c7d9e01",
        data: "2026-06-12",
        horario: "14:15",
        tipo: "Retorno",
        profissional: "Dra. Juliana Sena",
        especialidade: "Clínica Geral",
        subjetivo: "Retorno para avaliação de exames laboratoriais admissionais de rotina. Nega sintomas.",
        objetivo: "Exames laboratoriais normais: Hemograma sem atipias, TSH 1.82, Creatinina 0.8, Glicemia 88, Colesterol Total 178 mg/dL.",
        sinaisVitais: {
          pressaoArterial: "120/80",
          frequenciaCardiaca: 70,
          peso: 58.0,
          altura: 165,
          imc: 21.3,
        },
        avaliacao: "Checkup preventivo dentro dos padrões de normalidade (CID-10 Z00.0).",
        plano: "Manter hábitos saudáveis de alimentação e atividade física regular. Agendada revisão anual.",
        created_at: "2026-06-12T14:40:00Z",
      },
    ],
    prescriptions: [
      {
        id: "rx-101",
        client_id: "e4a1f89b-9c7d-4a1b-8e2f-1a3b5c7d9e01",
        data: "2026-09-25",
        medicamento: "Desonida 0,05% Loção Cremosa",
        dosagem: "Frasco 60g",
        via: "Tópico",
        posologia: "Aplicar fina camada sobre as lesões 1x à noite",
        duracao: "7 dias",
        ativo: true,
        instrucoes: "Não aplicar em áreas extensas. Suspender após melhora do eritema.",
      },
      {
        id: "rx-102",
        client_id: "e4a1f89b-9c7d-4a1b-8e2f-1a3b5c7d9e01",
        data: "2026-09-25",
        medicamento: "Creme Emoliente com Ceramidas",
        dosagem: "Bisnaga 200g",
        via: "Tópico",
        posologia: "Aplicar em todo o corpo 2 vezes ao dia",
        duracao: "Uso contínuo",
        ativo: true,
        instrucoes: "Aplicar preferencialmente até 3 minutos após o banho.",
      },
    ],
  },

  // Carlos Eduardo Nogueira
  "b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e": {
    client_id: "b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
    medicalHistory: {
      alergias: ["Nenhuma conhecida"],
      comorbidades: ["Hipertensão Arterial Sistêmica Estágio 1", "Dislipidemia"],
      medicamentosUsoContinuo: ["Losartana Potássica 50mg (1x ao dia pela manhã)", "Rosuvastatina 10mg (1x à noite)"],
      tipoSanguineo: "O+",
      historicoCirurgico: "Meniscectomia parcial joelho direito (artroscopia em 2021).",
      historicoFamiliar: "Pai faleceu por infarto agudo do miocárdio aos 62 anos.",
      habitosVida: {
        tabagismo: "Ex-fumante",
        etilismo: "Consumo social",
        atividadeFisica: "Intensa (4-7x/sem)",
      },
      observacoesGerais: "Praticante de corrida de longa distância (meia-maratona). Acompanhamento cardiológico regular.",
      updated_at: "2026-09-18T11:00:00Z",
    },
    evolutions: [
      {
        id: "evo-201",
        client_id: "b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
        data: "2026-09-18",
        horario: "11:20",
        tipo: "Consulta",
        profissional: "Dra. Juliana Sena",
        especialidade: "Clínica Geral & Cardiologia Preventiva",
        subjetivo: "Paciente em acompanhamento de HAS e controle lipídico. Relata ótima tolerância medicamentosa e ausência de tonturas ou palpitações durante treinos aeróbicos.",
        objetivo: "BEG, lúcido e orientado, eupneico. RCR 2T BNF sem sopros. Murmúrio vesicular presente bilateral sem ruídos adventícios. Abdome flácido e indolor.",
        sinaisVitais: {
          pressaoArterial: "124/82",
          frequenciaCardiaca: 58,
          temperatura: 36.5,
          peso: 76.2,
          altura: 178,
          imc: 24.0,
        },
        avaliacao: "Hipertensão controlada farmacologicamente (CID-10 I10); Bradicardia fisiológica de atleta.",
        plano: "1. Manter Losartana 50mg/dia e Rosuvastatina 10mg/dia.\n2. Solicitado ECG de repouso e Teste Ergométrico para liberação desportiva de maratona.\n3. Perfil lipídico e função renal para retorno em 60 dias.",
        created_at: "2026-09-18T11:45:00Z",
      },
    ],
    prescriptions: [
      {
        id: "rx-201",
        client_id: "b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
        data: "2026-09-18",
        medicamento: "Losartana Potássica",
        dosagem: "50 mg",
        via: "Oral",
        posologia: "Tomar 1 comprimido pela manhã em jejum",
        duracao: "Uso contínuo (receita 6 meses)",
        ativo: true,
      },
      {
        id: "rx-202",
        client_id: "b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
        data: "2026-09-18",
        medicamento: "Rosuvastatina Cálcica",
        dosagem: "10 mg",
        via: "Oral",
        posologia: "Tomar 1 comprimido à noite antes de dormir",
        duracao: "Uso contínuo",
        ativo: true,
      },
    ],
  },
};
